/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wastemainapp;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class HouseholdGUI extends javax.swing.JFrame {
    String contact, name, eircode, description;
    ArrayList<HouseHold> houseHold; 
    /**
     * Creates new form Household
     */
    public HouseholdGUI() {
        initComponents();
        houseHold = new ArrayList<>(); //create arraylist empty
        load(); //load data
    }
    //check Eircode
    private boolean isEircode(String eircode) {
    for (int i = 0; i < houseHold.size(); i++) { //loop from 0 to the end
        HouseHold h = houseHold.get(i); // Each iteration will take one HouseHold to check. 
        if (h.getEircode().equalsIgnoreCase(eircode)) { //If the eircode is the same (case insensitive)
            return true;  // eircode is exists
        }
    }
    return false; // not exists
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        householdinfomationLbl = new javax.swing.JLabel();
        eircodeLbl = new javax.swing.JLabel();
        eircodeTF = new javax.swing.JTextField();
        contactLbl = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        descriptionLbl = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Household Information");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        householdinfomationLbl.setBackground(new java.awt.Color(255, 255, 255));
        householdinfomationLbl.setFont(new java.awt.Font("STIX Two Text", 1, 25)); // NOI18N
        householdinfomationLbl.setForeground(new java.awt.Color(38, 37, 77));
        householdinfomationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        householdinfomationLbl.setText("HOUSEHOLD INFOMATION");
        jPanel1.add(householdinfomationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 400, 70));

        eircodeLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        eircodeLbl.setForeground(new java.awt.Color(38, 37, 77));
        eircodeLbl.setText("Eircode");
        jPanel1.add(eircodeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 98, -1, 20));

        eircodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eircodeTFActionPerformed(evt);
            }
        });
        jPanel1.add(eircodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 88, 340, 40));

        contactLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        contactLbl.setForeground(new java.awt.Color(38, 37, 77));
        contactLbl.setText("Contact");
        jPanel1.add(contactLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 167, -1, 20));

        contactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTFActionPerformed(evt);
            }
        });
        jPanel1.add(contactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 157, 340, 40));

        backBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 375, 100, 40));

        registerBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 102, 102));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 375, 110, 40));

        displayBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(0, 102, 102));
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 375, 110, 40));

        nameLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(38, 37, 77));
        nameLbl.setText("Name");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 235, -1, -1));
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 227, 340, 40));

        descriptionLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        descriptionLbl.setForeground(new java.awt.Color(38, 37, 77));
        descriptionLbl.setText("How many people in your family?");
        jPanel1.add(descriptionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 293, -1, -1));

        descriptionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTFActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 313, 430, 40));

        clearBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 102, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 375, 100, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eircodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eircodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eircodeTFActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainAppGUI mg = new MainAppGUI(); //create a new object for MainAppGui
        mg.setVisible(true); // show the MainAppGui
        dispose(); // close the windown current
    }//GEN-LAST:event_backBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        contact = contactTF.getText().trim(); //get data and trim space
        name = nameTF.getText().trim(); //get data and trim space
        eircode = eircodeTF.getText().trim(); //get data and trim space
        description = descriptionTF.getText().trim(); //get data and trim space
        //check empty 
        if(eircode.isEmpty() || contact.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter both Eircode and contact");
            return;
        }
        //check eircode is exists
        if (isEircode (eircode)) {
            JOptionPane.showMessageDialog(this,"This Eircode already exists. Please enter a new one.");
        return;
    }
       HouseHold h = new HouseHold(contact, name, eircode, description); // create a new object
       houseHold.add(h); // Add in list of memory
        //save the list to a file
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("household.dat"))) {
            oos.writeObject(houseHold);
            JOptionPane.showMessageDialog(this,"Saved household successfully");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,"File output error: " +e.getMessage());
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if(houseHold.isEmpty()){
            JOptionPane.showMessageDialog(this,"No households to display.");
        }
        for (int i = 0; i<houseHold.size();i++){ // loop from 0 to the end
            HouseHold tempH = houseHold.get(i); //get data
            JOptionPane.showMessageDialog(this,"House Hold: "+ tempH.getContact()+", "+ tempH.getName()+", "+ tempH.getEircode()+", "+tempH.getDescription()); //show data
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void contactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTFActionPerformed

    private void descriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTFActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        contactTF.setText(""); // an empty string.
        nameTF.setText(""); // an empty string.
        eircodeTF.setText(""); // an empty string.
        descriptionTF.setText(""); // an empty string.
    }//GEN-LAST:event_clearBtnActionPerformed

    private void load(){
      //  houseHold = new ArrayList<>();//always a empty list already
        try(ObjectInputStream oStream = new ObjectInputStream(new FileInputStream("household.dat"))){ //open file to read
            houseHold = (ArrayList<HouseHold>)oStream.readObject(); // read data and cast to ArrayList<HouseHold> and put result in the household
            JOptionPane.showMessageDialog(this,"File loaded successfully"); // show message
        }
        catch(FileNotFoundException e){ //file not found
            houseHold = new ArrayList<>(); //if don't have file ==> create list empty to avoid null
        }
        catch(ClassNotFoundException e){ // class not found (changed name)
            JOptionPane.showMessageDialog(this,"An error occurred while reading the file. Make sure the class matches the saved data");
        }
        catch(IOException e){ //file wrong, wrong format..
            JOptionPane.showMessageDialog(this,"An error occurred while reading the file."+e.getMessage());
            houseHold = new ArrayList<>(); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HouseholdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HouseholdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HouseholdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HouseholdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HouseholdGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JTextField contactTF;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel eircodeLbl;
    private javax.swing.JTextField eircodeTF;
    private javax.swing.JLabel householdinfomationLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables

}
