/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wastemainapp;

/**
 *
 * @author Hoang
 */
public class MainAppGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainAppGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        collectingwasteappLbl = new javax.swing.JLabel();
        householdBtn = new javax.swing.JButton();
        wasteentryBtn = new javax.swing.JButton();
        wastetypeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Collecting Waste Application");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        collectingwasteappLbl.setFont(new java.awt.Font("STIX Two Text", 1, 24)); // NOI18N
        collectingwasteappLbl.setForeground(new java.awt.Color(0, 102, 102));
        collectingwasteappLbl.setText("COLLECTING WASTE APP");
        jPanel1.add(collectingwasteappLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        householdBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        householdBtn.setForeground(new java.awt.Color(0, 102, 102));
        householdBtn.setText("Household");
        householdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                householdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(householdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, 60));

        wasteentryBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        wasteentryBtn.setForeground(new java.awt.Color(0, 102, 102));
        wasteentryBtn.setText("Waste Entry");
        wasteentryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wasteentryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(wasteentryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 230, 60));

        wastetypeBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        wastetypeBtn.setForeground(new java.awt.Color(0, 102, 102));
        wastetypeBtn.setText("Waste Type");
        wastetypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wastetypeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(wastetypeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 230, 60));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wastetypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wastetypeBtnActionPerformed
        // TODO add your handling code here:
        WasteTypeGUI wt = new WasteTypeGUI();
        wt.setVisible(true);
        dispose();
    }//GEN-LAST:event_wastetypeBtnActionPerformed

    private void householdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_householdBtnActionPerformed
        // TODO add your handling code here:
        HouseholdGUI hg = new HouseholdGUI();
        hg.setVisible(true);
        dispose();
    }//GEN-LAST:event_householdBtnActionPerformed

    private void wasteentryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wasteentryBtnActionPerformed
        // TODO add your handling code here:
        WasteEntryGUI we = new WasteEntryGUI();
        we.setVisible(true);
        dispose();
    }//GEN-LAST:event_wasteentryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel collectingwasteappLbl;
    private javax.swing.JButton householdBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton wasteentryBtn;
    private javax.swing.JButton wastetypeBtn;
    // End of variables declaration//GEN-END:variables
}
