/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wastemainapp;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Hoang
 */
public class WasteEntryGUI extends javax.swing.JFrame {
    //Variables
    String eircode, date, wasteType, file;
    double weight;
    ArrayList<WasteEntry> list; // list contain WasteEntry
   

    /**
     * Creates new form WasteEntry
     */
    public WasteEntryGUI() {
        initComponents(); //Create GUI
        list = new ArrayList<>(); // declare empty Arraylist
    }
    private boolean isEircode(String eircode) {
        ArrayList<HouseHold> hList; // declare variable hList (no data)
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("household.dat"))) { //open the household.dat file
            //Read household.dat file -> list Household
            hList = (ArrayList<HouseHold>) ois.readObject(); // read the data and cast to Arraylist<HouseHold>
            //loop all Household in the file
            for (int i = 0; i < hList.size(); i++) {
                HouseHold h = hList.get(i);
                //check eircode
                if (h.getEircode().equalsIgnoreCase(eircode)) {
                    return true; // found
                }
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "The data file household.dat was not found. Please save before trying to load.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file. Make sure the class matches the saved data");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file." + e.getMessage());
        }
        return false; // not found
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        wasteEntryLbl = new javax.swing.JLabel();
        eircodeLbl = new javax.swing.JLabel();
        eircodeTF = new javax.swing.JTextField();
        weightLbl = new javax.swing.JLabel();
        weightTF = new javax.swing.JTextField();
        wastetypeLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        saveBtn1 = new javax.swing.JButton();
        generalwasteRB = new javax.swing.JRadioButton();
        recyclingRB = new javax.swing.JRadioButton();
        organicwasteRB = new javax.swing.JRadioButton();
        clearBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waste Entry");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wasteEntryLbl.setFont(new java.awt.Font("STIX Two Text", 1, 25)); // NOI18N
        wasteEntryLbl.setForeground(new java.awt.Color(38, 37, 77));
        wasteEntryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wasteEntryLbl.setText("WASTE ENTRY");
        jPanel1.add(wasteEntryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        eircodeLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        eircodeLbl.setForeground(new java.awt.Color(38, 37, 77));
        eircodeLbl.setText("Eircode");
        jPanel1.add(eircodeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 90, -1, 20));

        eircodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eircodeTFActionPerformed(evt);
            }
        });
        jPanel1.add(eircodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 80, 340, 40));

        weightLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        weightLbl.setForeground(new java.awt.Color(38, 37, 77));
        weightLbl.setText("Weight");
        jPanel1.add(weightLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 150, -1, 20));
        jPanel1.add(weightTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 140, 340, 40));

        wastetypeLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        wastetypeLbl.setForeground(new java.awt.Color(38, 37, 77));
        wastetypeLbl.setText("Waste Type");
        jPanel1.add(wastetypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 231, -1, 20));

        backBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 390, -1, 40));

        displayBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(0, 102, 102));
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 390, -1, 40));

        dateLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(38, 37, 77));
        dateLbl.setText("Date");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 307, -1, 20));
        jPanel1.add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 297, 340, 40));

        saveBtn1.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        saveBtn1.setForeground(new java.awt.Color(0, 102, 102));
        saveBtn1.setText("Save");
        saveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 390, -1, 40));

        buttonGroup1.add(generalwasteRB);
        generalwasteRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        generalwasteRB.setForeground(new java.awt.Color(38, 37, 77));
        generalwasteRB.setText("General Waste");
        generalwasteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalwasteRBActionPerformed(evt);
            }
        });
        jPanel1.add(generalwasteRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 258, -1, -1));

        buttonGroup1.add(recyclingRB);
        recyclingRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        recyclingRB.setForeground(new java.awt.Color(38, 37, 77));
        recyclingRB.setText("Recycling");
        recyclingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclingRBActionPerformed(evt);
            }
        });
        jPanel1.add(recyclingRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 228, -1, -1));

        buttonGroup1.add(organicwasteRB);
        organicwasteRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        organicwasteRB.setForeground(new java.awt.Color(38, 37, 77));
        organicwasteRB.setText("Organic Waste");
        organicwasteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organicwasteRBActionPerformed(evt);
            }
        });
        jPanel1.add(organicwasteRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 198, -1, -1));

        clearBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 102, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 390, -1, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eircodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eircodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eircodeTFActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainAppGUI mg = new MainAppGUI(); //create a new object for MainAppGui
        mg.setVisible(true); // show the MainAppGui
        dispose(); // close the windown current
    }//GEN-LAST:event_backBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        load(); // load data
        if(list == null || list.size() == 0 ){ //list haven't the data
            JOptionPane.showMessageDialog(this, "No data to display");
            return;
        }
        //loop all in list
        for (int i = 0; i < list.size(); i++) {
        WasteEntry tempw = list.get(i);
        JOptionPane.showMessageDialog(this,"Waste Entry: " + tempw.getEircode() + ", "+ tempw.getWeight() + "kg, "+ tempw.getWasteType() + ", "+ tempw.getDate());
    }
    }//GEN-LAST:event_displayBtnActionPerformed

    
    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
        // TODO add your handling code here:
        // get the data
        eircode = eircodeTF.getText().trim();
        String weightStr = weightTF.getText().trim(); // because weight is double current so it need to change String to get data
        date = dateTF.getText().trim();
        // check empty data
        if (eircode.isEmpty() || weightStr.isEmpty() || date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill all information please!");
            return;
        }
        //parse weight
        try {
            weight = Double.parseDouble(weightStr);
            if (weight <= 0) {
                JOptionPane.showMessageDialog(this, "The weight must be greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "The weight must be a number");
            return;
        }
        //check Eircode
        if (!isEircode(eircode)) {
            JOptionPane.showMessageDialog(this, "The Eircode is not registered");
            return;
        }
        // Waste sorting and save by type button
        if (recyclingRB.isSelected()) {
            wasteType = "Recycling";
            file = "recycling.dat";
        } else if (organicwasteRB.isSelected()) {
            wasteType = "Organic Waste";
            file = "organic.dat";
        } else if (generalwasteRB.isSelected()) {
            wasteType = "General Waste";
            file = "general.dat";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a waste type.");
            return;
        }
        // load the data
        list = new ArrayList<>();
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file))) {
            list = (ArrayList<WasteEntry>) ois.readObject();
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "The data file was not found. Please save before trying to load.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file. Make sure the class matches the saved data");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file." + e.getMessage());
        }
        // create a new object (wasteEntry)
        WasteEntry w = new WasteEntry(eircode, weight, wasteType, date);
        list.add(w); //Add in current list
        //save 
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file))) {
            oos.writeObject(list);
            JOptionPane.showMessageDialog(this, "Saved entry to " + file + " successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage());
        }
    }//GEN-LAST:event_saveBtn1ActionPerformed
   
    private void load() {
        //identify file by radio 
        if (recyclingRB.isSelected()) {
            file = "recycling.dat";
        } else if (organicwasteRB.isSelected()) {
            file = "organic.dat";
        } else if (generalwasteRB.isSelected()) {
            file = "general.dat";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a waste type.");
            list = new ArrayList<>(); //avoid null
            return;
        }
        try (ObjectInputStream oStream = new ObjectInputStream(new FileInputStream(file))) {

            list = (ArrayList<WasteEntry>) oStream.readObject();
            JOptionPane.showMessageDialog(this, "File loaded successfully");

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "The data file " + file + " was not found. Please save before trying to load.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "An error occurred while reading the file. Make sure the class matches the saved data");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "An error occurred while reading the file. " + e.getMessage());
            list = new ArrayList<>();
        }

    }
    
    private void generalwasteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalwasteRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalwasteRBActionPerformed

    private void recyclingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclingRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recyclingRBActionPerformed

    private void organicwasteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organicwasteRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organicwasteRBActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        eircodeTF.setText(""); // an empty string.
        weightTF.setText(""); // an empty string.
        dateTF.setText(""); // an empty string.
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WasteEntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WasteEntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WasteEntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WasteEntryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WasteEntryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel eircodeLbl;
    private javax.swing.JTextField eircodeTF;
    private javax.swing.JRadioButton generalwasteRB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton organicwasteRB;
    private javax.swing.JRadioButton recyclingRB;
    private javax.swing.JButton saveBtn1;
    private javax.swing.JLabel wasteEntryLbl;
    private javax.swing.JLabel wastetypeLbl;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JTextField weightTF;
    // End of variables declaration//GEN-END:variables
}
