/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wastemainapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class WasteTypeGUI extends javax.swing.JFrame {

    /**
     * Creates new form WasteEntryGUI
     */
    public WasteTypeGUI() {
        initComponents();
        hideImages();
    }

    private void hideImages() { //the first we will hide all images
        organicwasteimage.setVisible(false);
        recyclingwasteimage.setVisible(false);
        generalwasteimage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        wastetypeLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();
        organicwasteRB = new javax.swing.JRadioButton();
        recyclingRB = new javax.swing.JRadioButton();
        generalwasteRB = new javax.swing.JRadioButton();
        clearBtn = new javax.swing.JButton();
        displayguideBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionsTA = new javax.swing.JTextArea();
        recyclingwasteimage = new javax.swing.JLabel();
        organicwasteimage = new javax.swing.JLabel();
        generalwasteimage = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waste Type");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wastetypeLbl.setFont(new java.awt.Font("STIX Two Text", 1, 25)); // NOI18N
        wastetypeLbl.setForeground(new java.awt.Color(38, 37, 77));
        wastetypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wastetypeLbl.setText("WASTE TYPE");
        jPanel1.add(wastetypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        categoryLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        categoryLbl.setForeground(new java.awt.Color(38, 37, 77));
        categoryLbl.setText("Category");
        jPanel1.add(categoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        instructionsLbl.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        instructionsLbl.setForeground(new java.awt.Color(38, 37, 77));
        instructionsLbl.setText("Instructions");
        jPanel1.add(instructionsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        buttonGroup1.add(organicwasteRB);
        organicwasteRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        organicwasteRB.setForeground(new java.awt.Color(38, 37, 77));
        organicwasteRB.setText("Organic Waste");
        organicwasteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organicwasteRBActionPerformed(evt);
            }
        });
        jPanel1.add(organicwasteRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        buttonGroup1.add(recyclingRB);
        recyclingRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        recyclingRB.setForeground(new java.awt.Color(38, 37, 77));
        recyclingRB.setText("Recycling");
        recyclingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclingRBActionPerformed(evt);
            }
        });
        jPanel1.add(recyclingRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        buttonGroup1.add(generalwasteRB);
        generalwasteRB.setFont(new java.awt.Font("STIX Two Math", 1, 18)); // NOI18N
        generalwasteRB.setForeground(new java.awt.Color(38, 37, 77));
        generalwasteRB.setText("General Waste");
        generalwasteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalwasteRBActionPerformed(evt);
            }
        });
        jPanel1.add(generalwasteRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        clearBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 102, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 395, 90, 40));

        displayguideBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        displayguideBtn.setForeground(new java.awt.Color(0, 102, 102));
        displayguideBtn.setText("Display Guide");
        displayguideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayguideBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayguideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 395, 160, 40));

        backBtn.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 395, 110, 40));

        instructionsTA.setEditable(false);
        instructionsTA.setColumns(20);
        instructionsTA.setFont(new java.awt.Font("STIX Two Math", 0, 14)); // NOI18N
        instructionsTA.setLineWrap(true);
        instructionsTA.setRows(5);
        instructionsTA.setWrapStyleWord(true);
        jScrollPane1.setViewportView(instructionsTA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 101, 416, 51));

        recyclingwasteimage.setBackground(new java.awt.Color(217, 255, 172));
        recyclingwasteimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recycling waste.png"))); // NOI18N
        jPanel1.add(recyclingwasteimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        organicwasteimage.setBackground(new java.awt.Color(217, 255, 172));
        organicwasteimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organics waste.jpg"))); // NOI18N
        jPanel1.add(organicwasteimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        generalwasteimage.setBackground(new java.awt.Color(217, 255, 172));
        generalwasteimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general waste.jpeg"))); // NOI18N
        jPanel1.add(generalwasteimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainAppGUI mg = new MainAppGUI(); //create a new object for MainAppGui
        mg.setVisible(true); // show the MainAppGui
        dispose(); // close the windown current
    }//GEN-LAST:event_backBtnActionPerformed

    private void organicwasteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organicwasteRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organicwasteRBActionPerformed

    private void recyclingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclingRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recyclingRBActionPerformed

    private void generalwasteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalwasteRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalwasteRBActionPerformed

    private void displayguideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayguideBtnActionPerformed
        // TODO add your handling code here:
        if (!organicwasteRB.isSelected() && !recyclingRB.isSelected() && !generalwasteRB.isSelected()) { //have to selected least one type
            JOptionPane.showMessageDialog(this, "Let select a waste type please!");
            return;
        }

        hideImages(); // hide images

        if (organicwasteRB.isSelected()) { // if choose the organic waste radio button, we will show text and image of organic waste
            instructionsTA.setText("""
                            Organic waste includes food scraps, fruit and vegetable peels, tea bags and cofee grounds, eggshells, garden waste....
                            - Don't forget do not include: plastic or metal, glass, liquids or oils.
                            - Put them in the green bins.""");
            organicwasteimage.setVisible(true);
        } else if (recyclingRB.isSelected()) { // if choose the recycling waste radio button, we will show text and image of recycling waste
            instructionsTA.setText("""
                            Recycling waste includes paper, cardboard, bottles and containers, metal cans...
                            - Don't forget do not include: Food scraps, batteries or electronics. 
                            - Make sure all items are clean, dry and empty before put them in the navy blue bins.""");
            recyclingwasteimage.setVisible(true);
        } else if (generalwasteRB.isSelected()) { // if choose the general waste radio button, we will show text and image of general waste
            instructionsTA.setText("""
                            General waste is everything that can't be recycled or composted. 
                            - Don't forget do not include: batteries or electronics. 
                            - Put them in the black bins.""");
            generalwasteimage.setVisible(true);
        }
    }//GEN-LAST:event_displayguideBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        instructionsTA.setText(""); // an empty string.
        hideImages(); // hide all images
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WasteTypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WasteTypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WasteTypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WasteTypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WasteTypeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton displayguideBtn;
    private javax.swing.JRadioButton generalwasteRB;
    private javax.swing.JLabel generalwasteimage;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JTextArea instructionsTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton organicwasteRB;
    private javax.swing.JLabel organicwasteimage;
    private javax.swing.JRadioButton recyclingRB;
    private javax.swing.JLabel recyclingwasteimage;
    private javax.swing.JLabel wastetypeLbl;
    // End of variables declaration//GEN-END:variables
}
